[package]
name = "soundfont-deluge"
version = "0.1.0"
authors = ["PÃ¤r Bohrarper <par.bohrarper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.1.1"
riff = "1.0.1"